apiVersion: v1
kind: Service
metadata:
    name: account-server-service
    labels:
        type: ClusterIP
spec:
    type: ClusterIP
    selector:
        app: account-server
    ports:
        -   port: 3000